// ---
// relationships:
//   validates: github-release-executor
// ---

// Product-shaped Cargo/Homebrew platform contract tests.

    fn cargo_homebrew_platform_contract_workspace(label: &str) -> Workspace {
        let workspace = rust_homebrew_workspace(
            label,
            "[package]\nname = \"sample-tool\"\nversion = \"1.2.3\"\nedition = \"2021\"\ndescription = \"Sample command line tool\"\nlicense = \"MIT\"\n",
        );
        workspace
            .write(
                "Cargo.lock",
                "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"sample-tool\"\nversion = \"1.2.3\"\n",
            )
            .write(
                "component/src/main.rs",
                "fn main() { println!(\"sample-tool 1.2.3\"); }\n",
            );
        workspace
    }

    fn cargo_homebrew_platform_contract_step(workspace: &Workspace, job: &str) -> Value {
        converge(workspace.root(), WorkflowRole::Publish);
        job_steps(&publish_jobs(workspace.root()), job)
            .into_iter()
            .find(|step| step["run"].is_string())
            .unwrap_or_else(|| panic!("{job} has an emitted build body"))
    }

    fn cargo_homebrew_write_executable(path: &Path, body: &str) {
        std::fs::write(path, body).unwrap_or_else(|error| panic!("write {}: {error}", path.display()));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))
                .unwrap_or_else(|error| panic!("make {} executable: {error}", path.display()));
        }
    }

    fn cargo_homebrew_resolved_environment(
        step: &Value,
        workspace_root: &str,
        runner_root: &str,
    ) -> BTreeMap<String, String> {
        step_environment(step)
            .into_iter()
            .map(|(key, value)| {
                (
                    key,
                    value
                        .replace("${{ github.workspace }}", workspace_root)
                        .replace("${{ runner.temp }}", runner_root),
                )
            })
            .collect()
    }

    fn cargo_homebrew_execute_workspace_body(
        workspace: &Workspace,
        step: &Value,
        body: &str,
    ) -> (std::process::Output, PathBuf) {
        let runner = workspace.root().join("workspace-contract-runner");
        let stubs = runner.join("stubs");
        std::fs::create_dir_all(&stubs).expect("workspace contract stub directory");
        cargo_homebrew_write_executable(
            &stubs.join("cross"),
            "#!/usr/bin/env bash\nset -euo pipefail\nexec cargo \"$@\"\n",
        );
        let environment = cargo_homebrew_resolved_environment(
            step,
            workspace.root().to_str().expect("UTF-8 workspace path"),
            runner.to_str().expect("UTF-8 runner path"),
        );
        let archive = runner.join(
            environment
                .iter()
                .find_map(|(key, value)| key.ends_with("ARCHIVE").then_some(value))
                .expect("derived archive name"),
        );
        let mut command = std::process::Command::new("bash");
        command
            .args(["-c", body])
            .current_dir(workspace.root().join("component"))
            .env("RUNNER_TEMP", &runner)
            .env("LC_ALL", "C")
            .env("PATH", format!("{}:{}", stubs.display(), std::env::var("PATH").unwrap_or_default()));
        for (key, value) in environment {
            command.env(key, value);
        }
        (command.output().expect("workspace platform body runs"), archive)
    }

    #[test]
    #[ignore = "run through task cargo-homebrew:compatibility"]
    fn cargo_homebrew_platform_contract_workspace_member_reads_workspace_root_target() {
        let workspace = cargo_homebrew_platform_contract_workspace("workspace-root-output");
        let step = cargo_homebrew_platform_contract_step(
            &workspace,
            "intentional_build_component_cargo_archive_linux_x86_64",
        );
        let environment = cargo_homebrew_resolved_environment(
            &step,
            workspace.root().to_str().expect("UTF-8 workspace path"),
            workspace
                .root()
                .join("workspace-contract-runner")
                .to_str()
                .expect("UTF-8 runner path"),
        );
        let target_directory = PathBuf::from(
            environment
                .get("CARGO_TARGET_DIR")
                .expect("parsed job declares Cargo output"),
        );
        assert_eq!(
            target_directory.parent(),
            Some(workspace.root().join("target").as_path()),
            "the parsed job owns a workspace-root target directory"
        );

        let body = step["run"].as_str().expect("derived workspace body");
        let (output, archive) = cargo_homebrew_execute_workspace_body(&workspace, &step, body);
        assert!(
            output.status.success(),
            "real Cargo workspace body failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            target_directory
                .join("x86_64-unknown-linux-gnu/release/sample-tool")
                .is_file(),
            "real Cargo writes the workspace-root output consumed by the emitted body"
        );
        let listing = std::process::Command::new("tar")
            .args(["-tzf", archive.to_str().expect("UTF-8 archive path")])
            .output()
            .expect("workspace archive lists");
        assert!(listing.status.success());
        assert_eq!(
            String::from_utf8_lossy(&listing.stdout),
            "sample-tool\n",
            "the archive contains the binary read from the workspace-root target"
        );
    }

    #[test]
    #[ignore = "run through task cargo-homebrew:compatibility"]
    fn cargo_homebrew_platform_contract_member_relative_target_negative_control() {
        let workspace = cargo_homebrew_platform_contract_workspace("member-relative-negative");
        let step = cargo_homebrew_platform_contract_step(
            &workspace,
            "intentional_build_component_cargo_archive_linux_x86_64",
        );
        let body = step["run"].as_str().expect("derived workspace body");
        let mutant = body.replacen(
            "binary_path=\"${CARGO_TARGET_DIR}/",
            "binary_path=\"target/",
            1,
        );
        assert_ne!(mutant, body, "negative control reaches the emitted consumer");

        let (output, _) = cargo_homebrew_execute_workspace_body(&workspace, &step, &mutant);
        assert!(!output.status.success(), "member-relative lookup must fail");
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("chmod: cannot access 'target/x86_64-unknown-linux-gnu/release/sample-tool'"),
            "member-relative lookup dies at the emitted chmod input site: {stderr}"
        );
    }

    fn cargo_homebrew_bsdtar_image() -> &'static str {
        static IMAGE: std::sync::OnceLock<String> = std::sync::OnceLock::new();
        IMAGE.get_or_init(|| {
            let repository = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
            let dockerfile = std::fs::read_to_string(
                repository.join("scripts/ci/cargo-homebrew-bsdtar.Dockerfile"),
            )
            .expect("bsdtar Dockerfile is readable");
            assert!(
                dockerfile.lines().any(|line| {
                    line == "FROM debian:11.11-slim@sha256:f313b4bd62667092a59b3a664d7d3ab8b5e65f41675f48e81455a15dc5abe792"
                }),
                "bsdtar provisioning base is digest pinned"
            );
            assert!(
                dockerfile.contains("libarchive-tools=3.4.3-2+deb11u4"),
                "bsdtar provisioning selects the executed libarchive package"
            );
            let output = std::process::Command::new("docker")
                .args([
                    "build",
                    "--quiet",
                    "--platform",
                    "linux/amd64",
                    "--file",
                    "scripts/ci/cargo-homebrew-bsdtar.Dockerfile",
                    ".",
                ])
                .current_dir(repository)
                .output()
                .expect("Docker builds the pinned bsdtar environment");
            assert!(
                output.status.success(),
                "pinned bsdtar image build failed: {}",
                String::from_utf8_lossy(&output.stderr)
            );
            String::from_utf8(output.stdout)
                .expect("Docker image identity is UTF-8")
                .trim()
                .to_owned()
        })
    }

    fn cargo_homebrew_bsdtar_version() -> String {
        let output = std::process::Command::new("docker")
            .args([
                "run",
                "--rm",
                "--platform",
                "linux/amd64",
                "--env",
                "LC_ALL=C",
                cargo_homebrew_bsdtar_image(),
                "bsdtar",
                "--version",
            ])
            .output()
            .expect("pinned bsdtar reports its version");
        assert!(output.status.success());
        String::from_utf8(output.stdout).expect("bsdtar version is UTF-8")
    }

    fn cargo_homebrew_execute_bsdtar_body(
        workspace: &Workspace,
        step: &Value,
        body: &str,
    ) -> (std::process::Output, PathBuf) {
        use std::os::unix::fs::MetadataExt;

        let runner = workspace.root().join("bsdtar-contract-runner");
        let stubs = runner.join("stubs");
        std::fs::create_dir_all(&stubs).expect("bsdtar contract stub directory");
        cargo_homebrew_write_executable(
            &stubs.join("cargo"),
            r#"#!/usr/bin/env bash
set -euo pipefail
target=""
binary=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) target="$2"; shift 2 ;;
    --bin) binary="$2"; shift 2 ;;
    *) shift ;;
  esac
done
test -n "$target"
test -n "$binary"
mkdir -p "${CARGO_TARGET_DIR}/${target}/release"
printf '#!/usr/bin/env bash\nprintf "%s 1.2.3\\n"\n' "$binary" > "${CARGO_TARGET_DIR}/${target}/release/${binary}"
"#,
        );
        cargo_homebrew_write_executable(
            &stubs.join("tar"),
            "#!/usr/bin/env bash\nexec /usr/bin/bsdtar \"$@\"\n",
        );
        let environment = cargo_homebrew_resolved_environment(step, "/workspace", "/runner");
        let archive_name = environment
            .iter()
            .find_map(|(key, value)| key.ends_with("ARCHIVE").then_some(value.clone()))
            .expect("derived macOS archive name");
        let metadata = std::fs::metadata(workspace.root()).expect("workspace metadata");
        let mut command = std::process::Command::new("docker");
        command.args([
            "run",
            "--rm",
            "--platform",
            "linux/amd64",
            "--user",
            &format!("{}:{}", metadata.uid(), metadata.gid()),
            "--volume",
            &format!("{}:/workspace", workspace.root().display()),
            "--volume",
            &format!("{}:/runner", runner.display()),
            "--volume",
            &format!("{}:/stubs:ro", stubs.display()),
            "--workdir",
            "/workspace/component",
            "--env",
            "LC_ALL=C",
        ]);
        for (key, value) in environment {
            command.args(["--env", &format!("{key}={value}")]);
        }
        command
            .args([
                "--env",
                "PATH=/stubs:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "--env",
                "RUNNER_TEMP=/runner",
                cargo_homebrew_bsdtar_image(),
                "bash",
                "-c",
                body,
            ]);
        (
            command.output().expect("emitted body runs in bsdtar environment"),
            runner.join(archive_name),
        )
    }

    fn cargo_homebrew_inspect_bsdtar_archive(
        workspace: &Workspace,
        archive: &Path,
    ) -> std::process::Output {
        use std::os::unix::fs::MetadataExt;

        let runner = archive.parent().expect("archive directory");
        let metadata = std::fs::metadata(workspace.root()).expect("workspace metadata");
        std::process::Command::new("docker")
            .args([
                "run",
                "--rm",
                "--platform",
                "linux/amd64",
                "--user",
                &format!("{}:{}", metadata.uid(), metadata.gid()),
                "--volume",
                &format!("{}:/runner", runner.display()),
                "--env",
                "LC_ALL=C",
                "--env",
                &format!(
                    "ARCHIVE={}",
                    archive.file_name().expect("archive name").to_string_lossy()
                ),
                cargo_homebrew_bsdtar_image(),
                "bash",
                "-c",
                r#"set -euo pipefail
rm -rf /runner/inspect
mkdir /runner/inspect
bsdtar -xzf "/runner/${ARCHIVE}" -C /runner/inspect
set -- /runner/inspect/*
test "$#" -eq 1
printf 'name=%s\n' "$(basename "$1")"
printf 'mode=%s\n' "$(stat -c %a "$1")"
printf 'epoch=%s\n' "$(stat -c %Y "$1")"
"$1" --version
"#,
            ])
            .output()
            .expect("bsdtar archive inspection runs")
    }

    #[test]
    #[ignore = "run through task cargo-homebrew:compatibility"]
    fn cargo_homebrew_platform_contract_bsdtar_3_4_3_accepts_macos_archive() {
        assert!(
            cargo_homebrew_bsdtar_version().starts_with("bsdtar 3.4.3 - libarchive 3.4.3 "),
            "compatibility environment names exact bsdtar and libarchive versions"
        );
        let workspace = cargo_homebrew_platform_contract_workspace("bsdtar-positive");
        let step = cargo_homebrew_platform_contract_step(
            &workspace,
            "intentional_build_component_cargo_archive_macos_arm64",
        );
        let body = step["run"].as_str().expect("derived macOS body");
        let (output, archive) = cargo_homebrew_execute_bsdtar_body(&workspace, &step, body);
        assert!(
            output.status.success(),
            "macOS archive body failed under bsdtar 3.4.3: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        let inspection = cargo_homebrew_inspect_bsdtar_archive(&workspace, &archive);
        assert!(
            inspection.status.success(),
            "bsdtar archive inspection failed: {}",
            String::from_utf8_lossy(&inspection.stderr)
        );
        let inspection = String::from_utf8(inspection.stdout).expect("archive report is UTF-8");
        let mut lines = inspection.lines();
        assert_eq!(lines.next(), Some("name=sample-tool"), "archive content assertion");
        assert_eq!(lines.next(), Some("mode=755"), "archive executable-mode assertion");
        assert_eq!(lines.next(), Some("epoch=0"), "archive timestamp assertion");
        assert_eq!(lines.next(), Some("sample-tool 1.2.3"), "archived binary assertion");
    }

    #[test]
    #[ignore = "run through task cargo-homebrew:compatibility"]
    fn cargo_homebrew_platform_contract_gnu_sort_negative_control() {
        assert!(
            cargo_homebrew_bsdtar_version().starts_with("bsdtar 3.4.3 - libarchive 3.4.3 "),
            "negative control runs in the named bsdtar environment"
        );
        let workspace = cargo_homebrew_platform_contract_workspace("bsdtar-gnu-sort-negative");
        let step = cargo_homebrew_platform_contract_step(
            &workspace,
            "intentional_build_component_cargo_archive_macos_arm64",
        );
        let body = step["run"].as_str().expect("derived macOS body");
        let mutant = body.replacen("tar -cf -", "tar --sort=name -cf -", 1);
        assert_ne!(mutant, body, "negative control reaches the emitted tar command");

        let (output, _) = cargo_homebrew_execute_bsdtar_body(&workspace, &step, &mutant);
        assert!(!output.status.success(), "GNU-only tar option must fail");
        let stderr = String::from_utf8_lossy(&output.stderr);
        assert!(
            stderr.contains("bsdtar: Option --sort=name is not supported"),
            "GNU-only option dies at the bsdtar command site: {stderr}"
        );
    }
